CREATE TABLE Books(
	BookId NUMBER(10) PRIMARY KEY, 
	BookName VARCHAR2(255) NOT NULL,
	Author VARCHAR2(255) NOT NULL,
	Prof VARCHAR2(255),
	RelDate DATE,
	Layer VARCHAR2(255),
	Condition  VARCHAR2(255) NOT NULL,
	ISBN  VARCHAR2(255),
	Price  VARCHAR2(255) NOT NULL,
	CONSTRAINT Book_State FOREIGN KEY (State) REFERENCES Sate(StateId)
	CONSTRAINT Book_Buyer FOREIGN KEY (Buyer) REFERENCES User(UserId)
	CONSTRAINT Book_Seller FOREIGN KEY (Seller) REFERENCES Sate(UserId)
);

CREATE TABLE User(
	UserId NUMBER(10) PRIMARY KEY, 
	FirstName VARCHAR2(255) NOT NULL, 
	SecondName VARCHAR2(255), 
	Email VARCHAR2(255) NOT NULL, 
	Password VARCHAR2(255) NOT NULL
);

CREATE TABLE Status(
	StateId NUMBER(10) PRIMARY KEY,
	State VARCHAR2(255) NOT NULL
);
