CREATE TABLE Books(
	BookId INTEGER PRIMARY KEY AUTOINCREMENT, 
	BookName VARCHAR2(255) NOT NULL,
	Author VARCHAR2(255) NOT NULL,
	Prof VARCHAR2(255),
	RelDate DATE,
	Layer VARCHAR2(255),
	Condition  VARCHAR2(255) NOT NULL,
	ISBN  VARCHAR2(255),
	Price  VARCHAR2(255) NOT NULL,
	State INTEGER(10) NOT NULL,
	Buyer INTEGER(10),
	Seller INTEGER(10) NOT NULL,
	FOREIGN KEY (State) REFERENCES Sate(StateId),
	FOREIGN KEY (Buyer) REFERENCES User(UserId),
	FOREIGN KEY (Seller) REFERENCES Sate(UserId)
);

CREATE TABLE Users(
	UserId INTEGER PRIMARY KEY AUTOINCREMENT, 
	FirstName VARCHAR2(255) NOT NULL, 
	SecondName VARCHAR2(255), 
	Email VARCHAR2(255) NOT NULL, 
	Password VARCHAR2(255) NOT NULL
);

CREATE TABLE Status(
	StateId INTEGER PRIMARY KEY AUTOINCREMENT,
	State VARCHAR2(255) NOT NULL
);
